CREATE TABLE `HUMAN_RESOURCE` (
	`EMPLOYEE_ID`			VARCHAR(255)	NOT NULL,
	`PASSWORD`				VARCHAR(255)	NOT NULL,
	`JOIN_DATE`				DATETIME		NOT NULL,
	`JOIN_TYPE`				TINYINT(1)		NOT NULL,
	`NAME`					VARCHAR(255)	NOT NULL,
	`BIRTH`					VARCHAR(255)	NOT NULL,
	`DEPARTMENT_CD`			VARCHAR(255)	NOT NULL,
	`POSITION_CD`			VARCHAR(255)	NOT NULL,
	`YEARS_OF_SERVICE`		INT				NOT NULL,
	`EXTENSION_NUMBER`		VARCHAR(255)	NULL,
	`PHONE`					VARCHAR(255)	NOT NULL,
	`MAIN_NUMBER`			VARCHAR(255)	NULL,
	`EMAIL`					VARCHAR(255)	NOT NULL,
	`ADDRESS`				VARCHAR(255)	NOT NULL,
	`BANK`					VARCHAR(255)	NOT NULL,
	`ACCOUNT_NUMBER`		VARCHAR(255)	NOT NULL,
	`ACCOUNT_HOLDER`		VARCHAR(255)	NOT NULL,
	`APPROVAL_AUTHORITY`	TINYINT(1)		NOT NULL,
	`SIGNATURE`				LONGTEXT		NULL,
	`QUIT_DATE`				DATETIME		NULL,
	`QUIT_REASON`			VARCHAR(255)	NULL,
	`PROFILE`				MEDIUMBLOB		NULL,
	`REG_ID`				VARCHAR(255)	NOT NULL,
	`REG_DATE`				DATETIME		NOT NULL,
	`REG_MENU`				VARCHAR(255)	NOT NULL,
	`MOD_ID`				VARCHAR(255)	NOT NULL,
	`MOD_DATE`				DATETIME		NOT NULL,
	`MOD_MENU`				VARCHAR(255)	NOT NULL,
	CONSTRAINT PRIMARY KEY(EMPLOYEE_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



CREATE TABLE ROLE(
	ROLE_NUM INT AUTO_INCREMENT,
	ROLE_NAME VARCHAR(255) NOT NULL,
	CONSTRAINT PRIMARY KEY(ROLE_NUM)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

INSERT INTO ROLE VALUES(NULL, 'R001');
INSERT INTO ROLE VALUES(NULL, 'R002');
INSERT INTO ROLE VALUES(NULL, 'R003');



CREATE TABLE ACCOUNT_ROLE(
	ROLE_NUM INT,
	EMPLOYEE_ID VARCHAR(255),
	CONSTRAINT PRIMARY KEY(ROLE_NUM, EMPLOYEE_ID),
	CONSTRAINT FOREIGN KEY(ROLE_NUM) REFERENCES ROLE(ROLE_NUM) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY(EMPLOYEE_ID) REFERENCES HUMAN_RESOURCE(EMPLOYEE_ID) ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



CREATE TABLE `SCHEDULE` (
	`SCHEDULE_NO`		BIGINT	  		AUTO_INCREMENT,
	`EMPLOYEE_ID`		VARCHAR(255)	NOT NULL,
	`SCHEDULE_DATE`		DATETIME 		NOT NULL,
	`SCHEDULE_PLACE`	VARCHAR(255)  	NOT NULL,
	`SCHEDULE_CONTENTS`	VARCHAR(255)	NOT NULL,
	`SCHEDULE_TYPE`		TINYINT(1)		NOT NULL,
	`REG_ID`			VARCHAR(255)	NOT NULL,
	`REG_DATE`			DATETIME		NOT NULL,
	`REG_MENU`			VARCHAR(255)	NOT NULL,
	`MOD_ID`			VARCHAR(255)	NOT NULL,
	`MOD_DATE`			DATETIME		NOT NULL,
	`MOD_MENU`			VARCHAR(255)	NOT NULL,
	CONSTRAINT PRIMARY KEY(SCHEDULE_NO),
	CONSTRAINT FOREIGN KEY(EMPLOYEE_ID) REFERENCES HUMAN_RESOURCE(EMPLOYEE_ID) ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



/*
	CREATE TABLE `SCHEDULE_ATTENDEES` (
		`SCHEDULE_NO`	BIGINT			NOT NULL,
		`EMPLOYEE_ID`	VARCHAR(255)	NOT NULL,
		CONSTRAINT FOREIGN KEY(SCHEDULE_NO) REFERENCES SCHEDULE(SCHEDULE_NO) ON DELETE CASCADE,
		CONSTRAINT FOREIGN KEY(EMPLOYEE_ID) REFERENCES HUMAN_RESOURCE(EMPLOYEE_ID) ON DELETE CASCADE
	)
	ENGINE=InnoDB
	DEFAULT CHARSET=utf8mb4
	COLLATE=utf8mb4_general_ci;
*/



CREATE TABLE `ANNUAL_LEAVE` (
	`EMPLOYEE_ID`				VARCHAR(255)	NOT NULL,
	`OCCURRENCE_ANNUAL_LEAVE`	INT				NOT NULL DEFAULT 0,
	`TOTAL_ANNUAL_LEAVE`		INT				NOT NULL DEFAULT 0,
	`USED_ANNUAL_LEAVE`			INT				NOT NULL DEFAULT 0,
	`HAVE_ANNUAL_LEAVE`			INT				NOT NULL DEFAULT 0,
	`REG_ID`					VARCHAR(255)	NOT NULL,
	`REG_DATE`					DATETIME		NOT NULL,
	`REG_MENU`					VARCHAR(255)	NOT NULL,
	`MOD_ID`					VARCHAR(255)	NOT NULL,
	`MOD_DATE`					DATETIME		NOT NULL,
	`MOD_MENU`					VARCHAR(255)	NOT NULL,
	CONSTRAINT FOREIGN KEY(EMPLOYEE_ID) REFERENCES HUMAN_RESOURCE(EMPLOYEE_ID) ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



CREATE TABLE `ANNUAL_LEAVE_OCCURRED_HISTORY` (
	`ANNUAL_LEAVE_OCCURRED_HISTORY_NO`	BIGINT			AUTO_INCREMENT,
	`EMPLOYEE_ID`						VARCHAR(255)	NOT NULL,
	`OCCURRED_DATE`						DATETIME		NOT NULL,
	`OCCURRED_TYPE`						TINYINT(1)		NOT NULL,
	`OCCURRED_COUNT`					INT				NOT NULL,
	`DESCRIPTION`						VARCHAR(255)	NULL,
	`REG_ID`							VARCHAR(255)	NOT NULL,
	`REG_DATE`							DATETIME		NOT NULL,
	`REG_MENU`							VARCHAR(255)	NOT NULL,
	`MOD_ID`							VARCHAR(255)	NOT NULL,
	`MOD_DATE`							DATETIME		NOT NULL,
	`MOD_MENU`							VARCHAR(255)	NOT NULL,
	CONSTRAINT PRIMARY KEY(ANNUAL_LEAVE_OCCURRED_HISTORY_NO),
	CONSTRAINT FOREIGN KEY(EMPLOYEE_ID) REFERENCES HUMAN_RESOURCE(EMPLOYEE_ID) ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



CREATE TABLE `ANNUAL_LEAVE_USED_HISTORY` (
	`ANNUAL_LEAVE_USED_HISTORY_NO`	BIGINT			AUTO_INCREMENT,
	`EMPLOYEE_ID`					VARCHAR(255)	NOT NULL,
	`ANNUAL_LEAVE_START`			DATETIME		NOT NULL,
	`ANNUAL_LEAVE_END`				DATETIME		NOT NULL,
	`USED_ANNUAL_LEAVE_COUNT`		INT				NOT NULL,
	`REASON`						VARCHAR(255)	NULL,
	`REG_ID`						VARCHAR(255)	NOT NULL,
	`REG_DATE`						DATETIME		NOT NULL,
	`REG_MENU`						VARCHAR(255)	NOT NULL,
	`MOD_ID`						VARCHAR(255)	NOT NULL,
	`MOD_DATE`						DATETIME		NOT NULL,
	`MOD_MENU`						VARCHAR(255)	NOT NULL,
	CONSTRAINT PRIMARY KEY(ANNUAL_LEAVE_USED_HISTORY_NO),
	CONSTRAINT FOREIGN KEY(EMPLOYEE_ID) REFERENCES HUMAN_RESOURCE(EMPLOYEE_ID) ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



CREATE TABLE `ATTENDANCE` (
	`ATTENDANCE_NO`		BIGINT			AUTO_INCREMENT,
	`EMPLOYEE_ID`		VARCHAR(255)	NOT NULL,
	`ATTENDANCE_DATE`	DATETIME		NOT NULL,
	`ATTENDANCE_START`	DATETIME		NOT NULL,
	`ATTENDANCE_END`	DATETIME		NULL,
	`REG_ID`			VARCHAR(255)	NOT NULL,
	`REG_DATE`			DATETIME		NOT NULL,
	`REG_MENU`			VARCHAR(255)	NOT NULL,
	`MOD_ID`			VARCHAR(255)	NOT NULL,
	`MOD_DATE`			DATETIME		NOT NULL,
	`MOD_MENU`			VARCHAR(255)	NOT NULL,
	CONSTRAINT PRIMARY KEY(ATTENDANCE_NO),
	CONSTRAINT FOREIGN KEY(EMPLOYEE_ID) REFERENCES HUMAN_RESOURCE(EMPLOYEE_ID) ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



CREATE TABLE `TRANSFER` (
	`TRANSFER_NO`				BIGINT			AUTO_INCREMENT,
	`EMPLOYEE_ID`				VARCHAR(255)	NOT NULL,
	`NAME`						VARCHAR(255)	NOT NULL,
	`TRANSFER_DATE`				DATETIME		NOT NULL,
	`TRANSFER_TYPE_CD`			VARCHAR(255)	NOT NULL,
	`BEFORE_POSITION_CD`		VARCHAR(255)	NOT NULL,
	`TRANSFER_POSITION_CD`		VARCHAR(255)	NOT NULL,
	`BEFORE_DEPARTMENT_CD`		VARCHAR(255)	NOT NULL,
	`TRANSFER_DEPARTMENT_CD`	VARCHAR(255)	NOT NULL,
	`REG_ID`					VARCHAR(255)	NOT NULL,
	`REG_DATE`					DATETIME		NOT NULL,
	`REG_MENU`					VARCHAR(255)	NOT NULL,
	`MOD_ID`					VARCHAR(255)	NOT NULL,
	`MOD_DATE`					DATETIME		NOT NULL,
	`MOD_MENU`					VARCHAR(255)	NOT NULL,
	CONSTRAINT PRIMARY KEY(TRANSFER_NO),
	CONSTRAINT FOREIGN KEY(EMPLOYEE_ID) REFERENCES HUMAN_RESOURCE(EMPLOYEE_ID) ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



CREATE TABLE `NOTIFICATION` (
	`NOTIFICATION_NO`		BIGINT,
	`EMPLOYEE_ID`			VARCHAR(255)	NOT NULL,
	`NOTIFICATION_DATE`		DATETIME		NOT NULL,
	`NOTIFICATION_TITLE`	VARCHAR(255)	NOT NULL,
	`NOTIFICATION_CONTENTS`	VARCHAR(255)	NOT NULL,
	`REG_ID`				VARCHAR(255)	NOT NULL,
	`REG_DATE`				DATETIME		NOT NULL,
	`REG_MENU`				VARCHAR(255)	NOT NULL,
	`MOD_ID`				VARCHAR(255)	NOT NULL,
	`MOD_DATE`				DATETIME		NOT NULL,
	`MOD_MENU`				VARCHAR(255)	NOT NULL,
	CONSTRAINT PRIMARY KEY(NOTIFICATION_NO),
	CONSTRAINT FOREIGN KEY(EMPLOYEE_ID) REFERENCES HUMAN_RESOURCE(EMPLOYEE_ID) ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



CREATE
	FUNCTION FN_CODE_NM(AS_UP_CODE VARCHAR(20), AS_CODE VARCHAR(20)) RETURNS VARCHAR(100)
BEGIN
	DECLARE RTN_VAL VARCHAR(100);
	
	SELECT CODE_NAME INTO RTN_VAL
		FROM CODE
	WHERE CODE = AS_CODE AND UP_CODE = AS_UP_CODE LIMIT 1;
	
	RETURN RTN_VAL;
END;



CREATE
	FUNCTION FN_EMPLOYEE_ID() RETURNS VARCHAR(255)
BEGIN
	DECLARE RTN_VAL VARCHAR(255);
	DECLARE CURRENT_YEAR INT;
	SET CURRENT_YEAR = YEAR(NOW());
	
	SELECT IFNULL(MAX(CAST(SUBSTRING(EMPLOYEE_ID, LENGTH(CURRENT_YEAR) + 1) AS UNSIGNED)), 0) + 1 INTO RTN_VAL
		FROM HUMAN_RESOURCE
	WHERE SUBSTRING(EMPLOYEE_ID, 1, 4) = CURRENT_YEAR;
	
	SET RTN_VAL = CONCAT(CURRENT_YEAR, LPAD(RTN_VAL, 3, '0'));
	RETURN RTN_VAL;
END;



CREATE FUNCTION FN_TOTAL_ATTENDANCE_TIME(ATTENDANCE_START DATETIME, ATTENDANCE_END DATETIME) RETURNS DATETIME
BEGIN
	DECLARE TOTAL_SECONDS INT; /* 점심 시간 적용하지 않은 TOTAL_SECONDS */
	SET TOTAL_SECONDS = TIMESTAMPDIFF(SECOND, ATTENDANCE_START, COALESCE(ATTENDANCE_END, ATTENDANCE_START));
	
	IF TOTAL_SECONDS >= (3 * 3600) THEN /* 점심 시간(총 1시간) 제외 : 3시간 이상 근무 시 적용 */
		RETURN CASE
			WHEN TOTAL_SECONDS >= (4 * 3600) THEN COALESCE(ATTENDANCE_END, ATTENDANCE_START) - INTERVAL 1 HOUR
			ELSE COALESCE(ATTENDANCE_END, ATTENDANCE_START) /* ex) 9시 출근, 12시 30분 30초 퇴근 : 점심 시간 30분 30초만 제외 */
				 -
				 INTERVAL MINUTE(COALESCE(ATTENDANCE_END, ATTENDANCE_START)) MINUTE
				 -
				 INTERVAL SECOND(COALESCE(ATTENDANCE_END, ATTENDANCE_START)) SECOND
		END;
	ELSE /* 점심 시간 전에 퇴근한 경우 */
		RETURN COALESCE(ATTENDANCE_END, ATTENDANCE_START);
	END IF;
END;



/*
	-기본 : 8시간
	-연장 : 8시간 초과 - 기본(8시간)
	-야간 : 4시간 이상 연장한 시점부터 적용
*/
SELECT
	EMPLOYEE_ID, NAME, PROFILE, POSITION_CD_NAME, DEPARTMENT_CD_NAME,
	SEC_TO_TIME(SUM(TOTAL_SECONDS)) AS WEEK_ACCRUE, /* 누적 */
	SEC_TO_TIME /* 기본 */
	(
		SUM
		(
			CASE
				WHEN TOTAL_SECONDS <= (8 * 3600) THEN
					TOTAL_SECONDS
				ELSE (8 * 3600)
			END
		)
	) AS WEEK_DEFAULT,
	SEC_TO_TIME /* 연장 */
	(
		SUM
		(
			CASE
				WHEN TOTAL_SECONDS > (8 * 3600) THEN
					TOTAL_SECONDS - (8 * 3600)
				ELSE 0
			END
		)
	) AS WEEK_OVER,
	SEC_TO_TIME /* 야간 */
	(
		SUM
		(
			CASE
				WHEN TOTAL_SECONDS - (8 * 3600) > (4 * 3600) THEN
					TOTAL_SECONDS - (8 * 3600) - (4 * 3600)
				ELSE 0
			END
		)
	) AS WEEK_NIGHT
FROM
	(
		SELECT
			a.EMPLOYEE_ID, h.NAME, h.PROFILE,
			FN_CODE_NM(LEFT(h.POSITION_CD, 3), h.POSITION_CD) AS POSITION_CD_NAME,
			FN_CODE_NM(LEFT(h.DEPARTMENT_CD, 3), h.DEPARTMENT_CD) AS DEPARTMENT_CD_NAME,
			TIMESTAMPDIFF(SECOND, ATTENDANCE_START, FN_TOTAL_ATTENDANCE_TIME(ATTENDANCE_START, ATTENDANCE_END)) AS TOTAL_SECONDS /* 점심 시간 적용한 TOTAL_SECONDS */
		FROM
			ATTENDANCE a LEFT OUTER JOIN HUMAN_RESOURCE h
				ON a.EMPLOYEE_ID = h.EMPLOYEE_ID
		WHERE
			(ATTENDANCE_DATE BETWEEN '2023-11-01 00:00:00' AND '2023-11-31 23:59:59')
			AND DEPARTMENT_CD = 'D001'
			AND NAME LIKE '김%'
	) AS subquery
GROUP BY
	EMPLOYEE_ID;

/* ----------------------------------------------------------------------------------------------------------------------------------------------------------- */

INSERT INTO CODE VALUES('R001', 'R00', 'ADMIN', '', NOW(), '', '', NOW(), '');
INSERT INTO CODE VALUES('R002', 'R00', 'APPROVER', '', NOW(), '', '', NOW(), '');
INSERT INTO CODE VALUES('R003', 'R00', 'USER', '', NOW(), '', '', NOW(), '');
COMMIT;



INSERT INTO ATTENDANCE VALUES(NULL, '2023001', STR_TO_DATE('2023-11-20 09:00:00', '%Y-%m-%d %H:%i:%S'),
											   STR_TO_DATE('2023-11-20 09:00:00', '%Y-%m-%d %H:%i:%S'),
											   STR_TO_DATE('2023-11-20 18:30:30', '%Y-%m-%d %H:%i:%S'),
											   '2023001',
											   STR_TO_DATE('2023-11-20 09:00:00', '%Y-%m-%d %H:%i:%S'),
											   '',
											   '2023001',
											   STR_TO_DATE('2023-11-20 09:00:00', '%Y-%m-%d %H:%i:%S'),
											   '');